# Generated by Django 4.2.27 on 2026-01-01 23:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('genero', models.CharField(choices=[('accion', 'Acción'), ('aventura', 'Aventura'), ('rpg', 'RPG'), ('deportes', 'Deportes'), ('carreras', 'Carreras'), ('estrategia', 'Estrategia'), ('shooter', 'Shooter'), ('lucha', 'Lucha'), ('plataformas', 'Plataformas'), ('terror', 'Terror')], max_length=50, verbose_name='Género')),
                ('desarrolladora', models.CharField(max_length=200, verbose_name='Desarrolladora')),
                ('ano_lanzamiento', models.IntegerField(validators=[django.core.validators.MinValueValidator(2005), django.core.validators.MaxValueValidator(2016)], verbose_name='Año de Lanzamiento')),
                ('clasificacion', models.CharField(choices=[('E', 'E - Everyone (Todos)'), ('E10+', 'E10+ - Everyone 10+ (Todos +10)'), ('T', 'T - Teen (Adolescentes)'), ('M', 'M - Mature (Maduro)'), ('AO', 'AO - Adults Only (Solo Adultos)')], max_length=10, verbose_name='Clasificación Indicativa')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='juegos/', verbose_name='Imagen de Portada')),
                ('disponible', models.BooleanField(default=True, verbose_name='Disponible')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Juego',
                'verbose_name_plural': 'Juegos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=200, verbose_name='Nombre del Cliente')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.juego', verbose_name='Juego')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tienda.pedido', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Item de Pedido',
                'verbose_name_plural': 'Items de Pedido',
            },
        ),
    ]
