# Generated by Django 4.2.27 on 2026-01-01 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='uala_checkout_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL Checkout Ualá'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='uala_order_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ID Orden Ualá'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='uala_payment_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ID Pago Ualá'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='uala_status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado Ualá'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado'), ('cancelado', 'Cancelado'), ('pagado', 'Pagado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20, verbose_name='Estado'),
        ),
    ]
