# Generated by Django 4.2.27 on 2026-01-01 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_pedido_uala_checkout_url_pedido_uala_order_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='uala_checkout_url',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='uala_order_id',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='uala_payment_id',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='uala_status',
        ),
        migrations.AddField(
            model_name='pedido',
            name='mp_checkout_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL Checkout Mercado Pago'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='mp_payment_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ID Pago Mercado Pago'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='mp_preference_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ID Preferencia Mercado Pago'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='mp_status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado Mercado Pago'),
        ),
    ]
