# Generated by Django 4.2.27 on 2026-01-02 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_remove_pedido_uala_checkout_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='link_descarga',
            field=models.URLField(blank=True, help_text='URL del link de descarga del juego. Se mostrará al cliente después del pago confirmado.', max_length=500, null=True, verbose_name='Link de Descarga'),
        ),
    ]
