# Generated by Django 4.2.27 on 2026-01-02 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_juego_link_descarga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='imagen',
            field=models.URLField(blank=True, help_text='URL completa de la imagen del juego (ejemplo: https://ejemplo.com/imagen.jpg)', max_length=500, null=True, verbose_name='URL de Imagen de Portada'),
        ),
    ]
